name: Pipeline-PRD

on:
  push:
    branches: [ "main" ]

jobs:
  Integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ./publish
    - name: Upload Publish Directory as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish-artifact
        path: ./publish

  Deploy:

    runs-on: ubuntu-latest
    needs: Integration

    steps:
    - name: Download Publish Artifact
      uses: actions/download-artifact@v3
      with:
        name: publish-artifact
        path: ./publish
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './publish/appsettings.Production.json'
      env:
        MongoDBSettings.ConnectionString: ${{ secrets.CONNECTION_STRING_PRD }}
        EncryptionKey: ${{ secrets.ENCRYPTION_KEY_PRD }}
        Jwt.Key: ${{ secrets.JWT_KEY_PRD }}
        Jwt.Issuer: ${{ secrets.JWT_ISSUER_PRD }}
        EmailSettings.AccessKey: ${{ secrets.EMAIL_ACCESS_KEY_PRD }}
        EmailSettings.SecretKey: ${{ secrets.EMAIL_SECRET_KEY_PRD }}
        APIs.AuthUrl: ${{ secrets.AUTH_URL_PRD }}
        BucketSettings.AccessKey: ${{ secrets.BUCKET_ACCESS_KEY_PRD }}
        BucketSettings.SecretKey: ${{ secrets.BUCKET_SECRET_KEY_PRD }}
        BucketSettings.BucketName: ${{ secrets.BUCKET_NAME_PRD }}
    - name: Deploy to AWS Lambda
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD }}
        AWS_REGION: ${{ secrets.AWS_REGION_PRD }}
      run: |
        cd ./publish 
        zip -r function.zip .
        aws lambda update-function-code --function-name ${{ secrets.LAMBDA_NAME_PRD }} --zip-file fileb://function.zip
