name: Pipeline-HML

on:
  push:
    branches: [ "stage" ]

jobs:
  Integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ./publish

  Deploy:

    runs-on: ubuntu-latest
    needs: Integration

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Substituir arquivos de configuração
      run: |
        sed -i 's/SECRET-HML/${{ secrets.CONNECTION_STRING_HML }}/g' ./publish/appsettings.Development.json
        sed -i 's/SECRET-HML/${{ secrets.ENCRYPTION_KEY_HML }}/g' ./publish/appsettings.Development.json
        sed -i 's/SECRET-HML/${{ secrets.JWT_KEY_HML }}/g' ./publish/appsettings.Development.json
        sed -i 's/SECRET-HML/${{ secrets.JWT_ISSUER_HML }}/g' ./publish/appsettings.Development.json
        sed -i 's/SECRET-HML/${{ secrets.EMAIL_ACCESS_KEY_HML }}/g' ./publish/appsettings.Development.json
        sed -i 's/SECRET-HML/${{ secrets.EMAIL_SECRET_KEY_HML }}/g' ./publish/appsettings.Development.json
        sed -i 's/SECRET-HML/${{ secrets.BUCKET_ACCESS_KEY_HML }}/g' ./publish/appsettings.Development.json
        sed -i 's/SECRET-HML/${{ secrets.BUCKET_SECRET_KEY_HML }}/g' ./publish/appsettings.Development.json
        sed -i 's/SECRET-HML/${{ secrets.BUCKET_NAME_HML }}/g' ./publish/appsettings.Development.json
    - name: Publish .NET project
      run: dotnet publish -c Release -o ./publish
    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_HML }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_HML }}
        AWS_REGION: ${{ secrets.AWS_REGION_HML }}
      run: |
        cd ./publish
        zip -r function.zip .
        aws lambda update-function-code --function-name ${{ secrets.LAMBDA_NAME_HML }} --zip-file fileb://function.zip
