name: Pipeline-PRD

on:
  push:
    branches: [ "main" ]

jobs:
  Integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ./publish

  Deploy:

    runs-on: ubuntu-latest
    needs: Integration

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Substituir arquivos de configuração
      run: |
        sed -i 's/SECRET-PRD/${{ secrets.CONNECTION_STRING_PRD }}/g' ./publish/appsettings.Production.json
        sed -i 's/SECRET-PRD/${{ secrets.ENCRYPTION_KEY_PRD }}/g' ./publish/appsettings.Production.json
        sed -i 's/SECRET-PRD/${{ secrets.JWT_KEY_PRD }}/g' ./publish/appsettings.Production.json
        sed -i 's/SECRET-PRD/${{ secrets.JWT_ISSUER_PRD }}/g' ./publish/appsettings.Production.json
        sed -i 's/SECRET-PRD/${{ secrets.EMAIL_ACCESS_KEY_PRD }}/g' ./publish/appsettings.Production.json
        sed -i 's/SECRET-PRD/${{ secrets.EMAIL_SECRET_KEY_PRD }}/g' ./publish/appsettings.Production.json
        sed -i 's/SECRET-PRD/${{ secrets.BUCKET_ACCESS_KEY_PRD }}/g' ./publish/appsettings.Production.json
        sed -i 's/SECRET-PRD/${{ secrets.BUCKET_SECRET_KEY_PRD }}/g' ./publish/appsettings.Production.json
        sed -i 's/SECRET-PRD/${{ secrets.BUCKET_NAME_PRD }}/g' ./publish/appsettings.Production.json
    - name: Publish .NET project
      run: dotnet publish -c Release -o ./publish
    - name: Deploy to AWS Lambda
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD }}
        AWS_REGION: ${{ secrets.AWS_REGION_PRD }}
      run: |
        cd ./publish 
        zip -r function.zip .
        aws lambda update-function-code --function-name ${{ secrets.LAMBDA_NAME_PRD }} --zip-file fileb://function.zip
